### ISSUE TITLE
Inconsistency in nearest centroid calculation (python vs. sky)

### ISSUE THREAD

**Issue by sdesimone** [bigmlcom/python#158]
Take a plain-vanilla iris.csv-based cluster and use the inputs displayed in the attached image. Python will spit out the following, where there is a ~10% distance gap (4.38 vs. 4.09). While this is not much, it still hints at different implementations, i.e., to the possibility of larger deviations.

![pastedgraphic-7](https://cloud.githubusercontent.com/assets/917131/11535395/fe6d850c-9913-11e5-89c4-c6a88cc80678.png)

```
{   'centroid_id': u'000001',
    'centroid_name': u'Cluster 1',
    'distance': 0.43821355717700766}
```

This was the command used:

```
prediction = cluster.centroid({'petal length': 4.07, 'sepal width': 3.15, 'petal width': 1.51, 'sepal length' : 4.0, 'species' : 'iris-setosa'}, by_name=True)
```

**Comment by mmerce** [comment]
@sdesimone , we are looking into it, but it looks like the python bindings and remote centroid predictions match. We are checking the web interface code for predictions in case some bug was inadvertedly missed. @joseribes is helping with that. We'll keep you posted.

**Comment by mmerce** [comment]
@sdesimone, finally @joseribes has realized that the command you wrote as example had one typo in the class name: instead of "Iris-setosa" you typed "iris-setosa". This causes the mismatch. Please, try it and close if you find no more issues.

**Comment by sdesimone** [comment]
That was it! Sorry for messing things up. I will add an input validation step to Swift and ObjC bindings so this kind of problems can be caught promptly.
