### ISSUE TITLE
Test For Consistent LDA Predictions

### ISSUE THREAD

**Issue by charleslparker** [bigmlcom/python#181]
We need to make sure we put in a test that pulls down an LDA model from the server and makes sure predictions are consistent with those made on the server.  This can be done when the version of bigmlcom/streaming-lda deployed on bigmlcom/wintermute reaches 0.5.0 or greater.  Can we get a heads up from @jao / @ashenfad / @petersen-poul when this happens?

**Comment by mmerce** [comment]
Added to version 4.8.0. Closing.
