### ISSUE TITLE
Not working with python 3.6

### ISSUE THREAD

**Issue by lucianosb** [bigmlcom/python#195]
The binding is constantly giving me the following error when loading a remote topic_model or even a remote dataset:

    \bigml\bigmlconnection.py in json_load(content)
    118 
    119     """
    --> 120     return json.loads(content.decode('utf-8'), 'utf-8')
    121 
    122 

    TypeError: loads() takes 1 positional argument but 2 were given

I'm running Anaconda Python 3.6 under Windows 10. I created then a virtualenv with Python 3.5 and calling the topic_model worked fine.  So it seems to be an issue with Python 3.6.

**Comment by mmerce** [comment]
Solved in version 4.8.2. Please reopen if it does not work for you.

**Comment by lucianosb** [comment]
Just tested. Everything working fine now. 

Thanks @mmerce !

**Comment by mmerce** [comment]
Thanks @lucianosb for the feedback!
