### ISSUE TITLE
Handle field pagination in ensemble

### ISSUE THREAD

**Issue by KamalGalrani** [bigmlcom/python#260]
Ensemble fails to load when there are more that 1000 fields

To replicate

1. Train an ensemble with more that 1000 input_fields
2. Load the ensemble in the following way
```
from bigml.api import BigML
from bigml.ensemble import Ensemble

api = BigML(<username>, <api_key>)
Ensemble('ensemble/<ensemble_id>', api=api)
```

The above gives a KeyError since the objective_id isn't found in Ensemble.fields.

Reference: https://bigml.com/api/ensembles#es_filtering_and_paginating_fields_from_an_ensemble

**Comment by mmerce** [comment]
Thanks for the heads up! I'll add the default query_string to the function. However, please keep in mind that  in order to store locally your ensemble information you need to add the storage info to your connection

```python

from bigml.api import BigML
from bigml.ensemble import Ensemble

api = BigML(<username>, <api_key>, storage=<storage_directory>)
Ensemble('ensemble/<ensemble_id>', api=api)
```

**Comment by mmerce** [comment]
Adding the code to PR#263. Thanks a lot!
