### ISSUE TITLE
api.ok resource parameter cannot actually be a string

### ISSUE THREAD

**Issue by skelliest** [bigmlcom/python#316]
According to the docstring, the `resource` parameter to the `api.ok` method can be a string, presumably something like `api.ok('dataset/531634203851d61f730accad')`.

https://github.com/bigmlcom/python/blob/57644d89639d8eaa25399a8d0bf681f907a5012d/bigml/resourcehandler.py#L545

This results in an error `TypeError: string indices must be integers`, so the documentation on this function probably just needs to change. You can get the same functionality with

```
dataset = api.get_dataset('dataset/531634203851d61f730accad')
api.ok(dataset)
```

**Comment by mmerce** [comment]
@skelliest Thanks for the feedbac! It is indeed an error in the docs. We'll be correcting it in next version.

**Comment by mmerce** [comment]
Te docstring has been updated in version 5.0.0. Thanks again for the heads up.
