### ISSUE TITLE
Unexpected number of leaves by computing get_leaves()

### ISSUE THREAD

**Issue by DylanWangWQF** [bigmlcom/python#402]
```
model = Model(MODEL_ID, api=BigML(username=USERNAME, api_key=BB_KEY))
leaves = get_leaves(model)
print(len(leaves))
```
```
Output: 428 leaves
```
`428 leaves` are obviously incorrect, as shown in the model figure below. 
The error is probably comes from this line https://github.com/bigmlcom/python/blob/a372c5c0265d587b4ebb047a2257a8b5b27478bc/bigml/generators/model.py#L152
![Screenshot 2024-07-19 at 16 43 43](https://github.com/user-attachments/assets/b0c342a3-3e52-442e-93e5-268b5e67923f)

**Comment by mmerce** [comment]
Hi @DylanWangWQF.
This was indeed a mistake that has been fixed in #404. Thanks for the heads up!
